"use client";

import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { addEdge, Background, Controls, MiniMap, ReactFlow, useEdgesState, useNodesState, type Connection, type Edge, type Node as FlowNode } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import TestSession from "./test-session";

type NodeConfig={integrationId?:number;path?:string;method?:string;rubric?:string;passThreshold?:number;audioRecordingId?:number;transitionAudioId?:number};
type WorkflowNode={id:string;type:string;label:string;prompt?:string;position?:{x:number;y:number};config?:NodeConfig};
type WorkflowEdge={id:string;source:string;target:string;label?:string;condition?:string};
type Workflow={nodes:WorkflowNode[];edges:WorkflowEdge[]};
type AgentRecord={id:number;name:string;objective:string;globalPrompt:string;greeting:string;channel:string;model:string;voice:string;status:string;locale:string;providerPolicy:{llm:string[];stt:string[];tts:string[]};workflow:Workflow|WorkflowNode[];recordingEnabled:boolean;maxCallSeconds:number;humanHandoffNumber:string};
type NodeData={label:string;kind:string;prompt:string;config:NodeConfig;[key:string]:unknown};
type IntegrationOption={id:number;name:string;kind:string};
type RecordingOption={id:number;filename:string;locale:string};

const defaultWorkflow:Workflow={nodes:[
 {id:"trigger",type:"Trigger",label:"Inbound or outbound call",prompt:"Start when a call or web conversation connects.",position:{x:80,y:80}},
 {id:"identity",type:"Agent",label:"Greet and identify caller",prompt:"Disclose that you are an AI assistant and ask how you can help.",position:{x:380,y:80}},
 {id:"decision",type:"Router",label:"Choose next action",prompt:"Route based on caller intent and verified context.",position:{x:680,y:80}},
 {id:"action",type:"Tool",label:"Complete approved action",prompt:"Use only connected tools and confirm their result before claiming success.",position:{x:980,y:20}},
 {id:"handoff",type:"Handoff",label:"Transfer to a person",prompt:"Offer a human handoff when requested, required by policy, or confidence is low.",position:{x:980,y:180}},
 {id:"end",type:"End",label:"Summarize and finish",prompt:"Recap the confirmed outcome and close politely.",position:{x:1280,y:80}},
 {id:"post-call-qa",type:"QA",label:"Post-call quality review",position:{x:1580,y:80},config:{rubric:"Score resolution, accuracy, policy compliance, and handoff quality.",passThreshold:75}},
],edges:[
 {id:"e-trigger-identity",source:"trigger",target:"identity",label:"connected"},{id:"e-identity-decision",source:"identity",target:"decision",label:"intent known"},
 {id:"e-decision-action",source:"decision",target:"action",label:"approved",condition:"Tool action is allowed"},{id:"e-decision-handoff",source:"decision",target:"handoff",label:"escalate",condition:"Caller requests a person or policy requires it"},
 {id:"e-action-end",source:"action",target:"end",label:"done"},{id:"e-handoff-end",source:"handoff",target:"end",label:"transferred"},{id:"e-end-qa",source:"end",target:"post-call-qa",label:"after call"},
]};
const library=[["Agent","Agent step"],["Knowledge","Knowledge lookup"],["Tool","Tool call"],["Router","Branch / condition"],["Guardrail","Human approval"],["Handoff","Human handoff"],["Message","Send message"],["Audio","Play recording"],["Webhook","Post-call webhook"],["QA","LLM QA analysis"],["End","End run"]] as const;

export default function Studio({workspace,brand,initialAgent,integrations,recordings,openGenerator=false,starterTemplate}:{workspace:{id:number;name:string;role:string};brand:string;initialAgent:AgentRecord|null;integrations:IntegrationOption[];recordings:RecordingOption[];openGenerator?:boolean;starterTemplate?:string}){
 const preset=templatePreset(starterTemplate);const initial=initialAgent?workflowValue(initialAgent.workflow):preset.workflow;
 const[nodes,setNodes,onNodesChange]=useNodesState<FlowNode<NodeData>>(initial.nodes.map(toFlowNode));
 const[edges,setEdges,onEdgesChange]=useEdgesState<Edge>(initial.edges.map(toFlowEdge));
 const[selectedNode,setSelectedNode]=useState(nodes[0]?.id||"");const[selectedEdge,setSelectedEdge]=useState("");const[test,setTest]=useState(false);const[generator,setGenerator]=useState(openGenerator);const[callPanel,setCallPanel]=useState(false);
 const[toNumber,setToNumber]=useState("");const[callState,setCallState]=useState("");const[generateState,setGenerateState]=useState("");
 const[generateForm,setGenerateForm]=useState({callType:"inbound",useCase:"",description:"",locale:initialAgent?.locale||"auto"});
 const[saveState,setSaveState]=useState("Save changes");const[agentId,setAgentId]=useState<number|null>(initialAgent?.id||null);const[name,setName]=useState(initialAgent?.name||preset.name);
 const[objective,setObjective]=useState(initialAgent?.objective||preset.objective);
 const[globalPrompt,setGlobalPrompt]=useState(initialAgent?.globalPrompt||initialAgent?.objective||preset.globalPrompt);
 const[greeting,setGreeting]=useState(initialAgent?.greeting||preset.greeting);const[locale,setLocale]=useState(initialAgent?.locale||"auto");const[status,setStatus]=useState(initialAgent?.status||"draft");
 const[recordingEnabled,setRecordingEnabled]=useState(initialAgent?.recordingEnabled??false);
 const importInput=useRef<HTMLInputElement>(null);const current=nodes.find(node=>node.id===selectedNode);const currentEdge=edges.find(edge=>edge.id===selectedEdge);
 const flowDefinition=useMemo(()=>({nodes:nodes.map(fromFlowNode),edges:edges.map(fromFlowEdge)}),[nodes,edges]);

 function onConnect(connection:Connection){if(!connection.source||!connection.target||connection.source===connection.target)return;setEdges(rows=>addEdge({...connection,id:`e-${connection.source}-${connection.target}-${crypto.randomUUID().slice(0,8)}`,label:"condition"},rows));}
 function addNode(kind:string,label:string){if(kind==="Webhook"&&!integrations.length){setSaveState("Connect a webhook integration first");return}if(kind==="Audio"&&!recordings.length){setSaveState("Upload a recording first");return}const id=`${kind.toLowerCase()}-${crypto.randomUUID().slice(0,8)}`;const config:NodeConfig=kind==="Webhook"?{integrationId:integrations[0].id,path:"",method:"POST"}:kind==="QA"?{rubric:"Score resolution, accuracy, policy compliance, and handoff quality.",passThreshold:75}:kind==="Audio"?{audioRecordingId:recordings[0].id}:{};setNodes(rows=>[...rows,{id,type:"default",position:{x:140+(rows.length%4)*280,y:100+Math.floor(rows.length/4)*190},data:{kind,label,prompt:"",config},className:`flow-node flow-${kind.toLowerCase()}`}]);setSelectedNode(id);setSelectedEdge("");}
 function updateCurrent(patch:Partial<NodeData>){if(!current)return;setNodes(rows=>rows.map(node=>node.id===current.id?{...node,data:{...node.data,...patch}}:node));}
 function updateConfig(patch:Partial<NodeConfig>){if(current)updateCurrent({config:{...current.data.config,...patch}});}
 async function save(){setSaveState("Saving…");try{const body={id:agentId||undefined,name,objective,globalPrompt,greeting,channel:"voice + chat",model:initialAgent?.model||"gpt-4.1-mini",voice:initialAgent?.voice||"elevenlabs-rachel",locale,status,recordingEnabled,maxCallSeconds:initialAgent?.maxCallSeconds||1800,humanHandoffNumber:initialAgent?.humanHandoffNumber||"",providerPolicy:initialAgent?.providerPolicy||{llm:["openai","anthropic","groq"],stt:["deepgram","elevenlabs","openai"],tts:["elevenlabs","openai"],realtime:["livekit"]},workflow:flowDefinition};const response=await fetch("/api/agents",{method:agentId?"PATCH":"POST",headers:{"content-type":"application/json","x-workspace-id":String(workspace.id)},body:JSON.stringify(body)});const data=await response.json() as{agent?:{id:number};error?:string;detail?:string};if(!response.ok||!data.agent)throw new Error(data.detail||data.error||"Save failed");setAgentId(data.agent.id);setSaveState("Saved ✓");setTimeout(()=>setSaveState("Save changes"),1800)}catch(error){setSaveState(error instanceof Error?error.message:"Save failed")}}
 async function generateAgent(){setGenerateState("Generating workflow…");try{const response=await fetch("/api/agents/generate",{method:"POST",headers:{"content-type":"application/json","x-workspace-id":String(workspace.id)},body:JSON.stringify(generateForm)});const data=await response.json() as{agent?:AgentRecord;error?:string};if(!response.ok||!data.agent)throw new Error(data.error||"Agent generation failed");loadAgent(data.agent);setGenerator(false);setGenerateState("");setSaveState("Generated draft ✓")}catch(error){setGenerateState(error instanceof Error?error.message:"Agent generation failed")}}
 function loadAgent(agent:AgentRecord){const workflow=workflowValue(agent.workflow);setNodes(workflow.nodes.map(toFlowNode));setEdges(workflow.edges.map(toFlowEdge));setAgentId(agent.id);setName(agent.name);setObjective(agent.objective);setGlobalPrompt(agent.globalPrompt);setGreeting(agent.greeting);setLocale(agent.locale);setStatus(agent.status);setRecordingEnabled(agent.recordingEnabled??false);setSelectedNode(workflow.nodes[0]?.id||"");}
 async function startPhoneCall(){setCallState("Starting…");try{if(!agentId)throw new Error("Save the agent first");const response=await fetch("/api/calls",{method:"POST",headers:{"content-type":"application/json","x-workspace-id":String(workspace.id)},body:JSON.stringify({agentId,toNumber})});const data=await response.json() as{call?:{id:number;status:string};error?:string};if(!response.ok||!data.call)throw new Error(data.error||"Call could not be started");setCallState(`Call #${data.call.id} is ${data.call.status}`)}catch(error){setCallState(error instanceof Error?error.message:"Call could not be started")}}
 async function importDefinition(file:File){setSaveState("Importing…");try{if(file.size>128*1024)throw new Error("Definition is too large");const response=await fetch("/api/agents/definition",{method:"POST",headers:{"content-type":"application/json","x-workspace-id":String(workspace.id)},body:await file.text()});const data=await response.json() as{agent?:AgentRecord;error?:string};if(!response.ok||!data.agent)throw new Error(data.error||"Import failed");loadAgent(data.agent);setSaveState("Imported as draft ✓")}catch(error){setSaveState(error instanceof Error?error.message:"Import failed")}finally{if(importInput.current)importInput.current.value=""}}

 return <main className="studio"><header className="studio-head"><Link className="brand" href="/agents"><span className="brand-mark">{brand.slice(0,1).toUpperCase()}</span><span>{brand.toUpperCase()}</span></Link><div className="breadcrumb"><span>{workspace.name}</span><b>/</b><input className="agent-name-input" value={name} onChange={event=>setName(event.target.value)} aria-label="Agent name"/><em>{status}</em></div><div className="studio-actions"><Link className="icon-link" href="/agents">All agents</Link><Link className="icon-link" href="/operations">Operations</Link><Link className="icon-link" href="/recordings">Audio</Link><input ref={importInput} className="definition-input" type="file" accept="application/json,.json" onChange={event=>{const file=event.target.files?.[0];if(file)void importDefinition(file)}}/><button className="icon-btn" type="button" onClick={()=>importInput.current?.click()}>Import</button>{agentId?<a className="icon-link" href={`/api/agents/definition?id=${agentId}&workspace=${workspace.id}`}>Export</a>:null}<button className="icon-btn" type="button" onClick={()=>setGenerator(true)}>✦ Generate</button><button className="test-btn" type="button" onClick={()=>agentId?setTest(true):setSaveState("Save the agent first")}>Talk</button><button className="test-btn" type="button" onClick={()=>setCallPanel(true)}>Call</button><button className="save-btn" type="button" onClick={()=>void save()}>{saveState}</button></div></header>
 <div className="studio-grid"><aside className="rail"><button className="rail-active">⌘<small>Build</small></button><Link href="/recordings">♫<small>Audio</small></Link><Link href="/analytics">◉<small>Observe</small></Link><span/><Link href="/telephony">⚙<small>Settings</small></Link></aside>
 <aside className="node-library"><div><b>BUILD</b><span>{nodes.length} nodes</span></div><p>CONVERSATION</p>{library.slice(0,8).map(([kind,label])=><button key={kind} type="button" onClick={()=>addNode(kind,label)}><i>{nodeIcon(kind)}</i>{label}<span>＋</span></button>)}<p>AFTER CALL</p>{library.slice(8).map(([kind,label])=><button key={kind} type="button" onClick={()=>addNode(kind,label)}><i>{nodeIcon(kind)}</i>{label}<span>＋</span></button>)}</aside>
 <section className="studio-canvas"><ReactFlow nodes={nodes} edges={edges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={onConnect} onNodeClick={(_,node)=>{setSelectedNode(node.id);setSelectedEdge("")}} onEdgeClick={(_,edge)=>{setSelectedEdge(edge.id);setSelectedNode("")}} onPaneClick={()=>{setSelectedNode("");setSelectedEdge("")}} fitView minZoom={.15} maxZoom={2} deleteKeyCode={["Backspace","Delete"]}><Background gap={20} size={1}/><MiniMap pannable zoomable/><Controls/></ReactFlow></section>
 <aside className="inspector">{current?<NodeInspector node={current} integrations={integrations} recordings={recordings} updateCurrent={updateCurrent} updateConfig={updateConfig} close={()=>setSelectedNode("")} remove={()=>{setNodes(rows=>rows.filter(node=>node.id!==current.id));setEdges(rows=>rows.filter(edge=>edge.source!==current.id&&edge.target!==current.id));setSelectedNode("")}}/>:currentEdge?<EdgeInspector edge={currentEdge} setEdges={setEdges} close={()=>setSelectedEdge("")}/>:<GlobalInspector objective={objective} setObjective={setObjective} globalPrompt={globalPrompt} setGlobalPrompt={setGlobalPrompt} greeting={greeting} setGreeting={setGreeting} locale={locale} setLocale={setLocale} status={status} setStatus={setStatus} recordingEnabled={recordingEnabled} setRecordingEnabled={setRecordingEnabled}/>}</aside></div>
 {test&&agentId?<TestSession agentId={agentId} workspaceId={workspace.id} agentName={name} brand={brand} onClose={()=>setTest(false)}/>:null}
 {generator?<GeneratorModal form={generateForm} setForm={setGenerateForm} state={generateState} close={()=>setGenerator(false)} generate={()=>void generateAgent()}/>:null}
 {callPanel?<CallModal name={name} status={status} agentId={agentId} number={toNumber} setNumber={setToNumber} state={callState} close={()=>setCallPanel(false)} call={()=>void startPhoneCall()}/>:null}
 </main>;
}

function NodeInspector({node,integrations,recordings,updateCurrent,updateConfig,close,remove}:{node:FlowNode<NodeData>;integrations:IntegrationOption[];recordings:RecordingOption[];updateCurrent:(patch:Partial<NodeData>)=>void;updateConfig:(patch:Partial<NodeConfig>)=>void;close:()=>void;remove:()=>void}){return <><div className="inspector-title"><div><small>{node.data.kind.toUpperCase()}</small><b>{node.data.label}</b></div><button type="button" onClick={close}>×</button></div><label>NODE LABEL</label><input value={node.data.label} onChange={event=>updateCurrent({label:event.target.value})}/><label>INSTRUCTIONS</label><textarea value={node.data.prompt} onChange={event=>updateCurrent({prompt:event.target.value})}/>{node.data.kind==="Webhook"?<><label>INTEGRATION</label><select value={node.data.config.integrationId||""} onChange={event=>updateConfig({integrationId:Number(event.target.value)})}>{integrations.map(row=><option value={row.id} key={row.id}>{row.name} · {row.kind}</option>)}</select><label>RELATIVE PATH</label><input value={node.data.config.path||""} placeholder="/events/call-completed" onChange={event=>updateConfig({path:event.target.value})}/><label>METHOD</label><select value={node.data.config.method||"POST"} onChange={event=>updateConfig({method:event.target.value})}><option>POST</option><option>PUT</option><option>PATCH</option></select><p className="secure-note">The host and encrypted credential come from the workspace integration. Workflow JSON never contains API secrets.</p></>:null}{node.data.kind==="QA"?<><label>QUALITY RUBRIC</label><textarea value={node.data.config.rubric||""} onChange={event=>updateConfig({rubric:event.target.value})}/><label>PASS THRESHOLD</label><input type="number" min="0" max="100" value={node.data.config.passThreshold??75} onChange={event=>updateConfig({passThreshold:Number(event.target.value)})}/></>:null}{node.data.kind==="Audio"?<><label>AUDIO RECORDING</label><select value={node.data.config.audioRecordingId||""} onChange={event=>updateConfig({audioRecordingId:Number(event.target.value)})}>{recordings.map(row=><option value={row.id} key={row.id}>{row.filename} · {row.locale}</option>)}</select><p className="secure-note">Use reusable tenant audio for prompts, notices, hold messages, or transitions.</p></>:null}<button className="danger-outline" type="button" onClick={remove}>Delete node</button></>}
function EdgeInspector({edge,setEdges,close}:{edge:Edge;setEdges:ReturnType<typeof useEdgesState<Edge>>[1];close:()=>void}){return <><div className="inspector-title"><div><small>BRANCH</small><b>{edge.source} → {edge.target}</b></div><button type="button" onClick={close}>×</button></div><label>BRANCH LABEL</label><input value={String(edge.label||"")} onChange={event=>setEdges(rows=>rows.map(row=>row.id===edge.id?{...row,label:event.target.value}:row))}/><label>CONDITION</label><textarea value={String(edge.data?.condition||"")} onChange={event=>setEdges(rows=>rows.map(row=>row.id===edge.id?{...row,data:{...row.data,condition:event.target.value}}:row))}/><button className="danger-outline" type="button" onClick={()=>{setEdges(rows=>rows.filter(row=>row.id!==edge.id));close()}}>Delete branch</button></>}
function GlobalInspector(props:{objective:string;setObjective:(v:string)=>void;globalPrompt:string;setGlobalPrompt:(v:string)=>void;greeting:string;setGreeting:(v:string)=>void;locale:string;setLocale:(v:string)=>void;status:string;setStatus:(v:string)=>void;recordingEnabled:boolean;setRecordingEnabled:(v:boolean)=>void}){return <><div className="inspector-title"><div><small>AGENT</small><b>Global settings</b></div></div><label>AGENT OBJECTIVE</label><textarea value={props.objective} onChange={event=>props.setObjective(event.target.value)}/><label>GLOBAL PROMPT</label><textarea value={props.globalPrompt} onChange={event=>props.setGlobalPrompt(event.target.value)}/><label>GREETING</label><textarea value={props.greeting} onChange={event=>props.setGreeting(event.target.value)}/><label>LANGUAGE POLICY</label><select value={props.locale} onChange={event=>props.setLocale(event.target.value)}><option value="auto">Auto-detect supported languages</option><option value="ar">العربية</option><option value="en-US">English (USA)</option><option value="en-GB">English (UK)</option><option value="hi-IN">हिन्दी</option><option value="hi-en">Hinglish</option></select><label>DEPLOYMENT</label><select value={props.status} onChange={event=>props.setStatus(event.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="paused">Paused</option></select><div className="guardrail"><div><b>Call recording</b><small>Disclosure and separate consent required</small></div><button type="button" aria-pressed={props.recordingEnabled} onClick={()=>props.setRecordingEnabled(!props.recordingEnabled)}>{props.recordingEnabled?"On":"Off"}</button></div><p className="secure-note">Recording is off by default. When enabled, the runtime still fails closed unless the caller received an explicit recording disclosure and current recording consent is recorded separately from voice-contact consent.</p><p className="secure-note">Connect node handles to create branches, then click an edge to name its condition.</p></>}
function GeneratorModal({form,setForm,state,close,generate}:{form:{callType:string;useCase:string;description:string;locale:string};setForm:(v:{callType:string;useCase:string;description:string;locale:string})=>void;state:string;close:()=>void;generate:()=>void}){return <div className="modal-backdrop"><div className="product-modal" role="dialog" aria-label="Generate agent"><div className="panel-head"><div><small>AGENT BUILDER</small><h2>Generate from a use case</h2></div><button type="button" onClick={close}>×</button></div><p>Describe what the agent should do. The model creates a safe, editable branching draft.</p><label>Call type<select value={form.callType} onChange={event=>setForm({...form,callType:event.target.value})}><option value="inbound">Inbound — customers call AI</option><option value="outbound">Outbound — AI calls customers</option><option value="both">Inbound and outbound</option></select></label><label>Use case<input placeholder="Lead qualification, front desk, customer support" value={form.useCase} onChange={event=>setForm({...form,useCase:event.target.value})}/></label><label>Activity description<textarea placeholder="Describe goals, allowed actions, handoff rules, and policies." value={form.description} onChange={event=>setForm({...form,description:event.target.value})}/></label><label>Language<select value={form.locale} onChange={event=>setForm({...form,locale:event.target.value})}><option value="auto">Auto-detect</option><option value="ar">Arabic</option><option value="en-US">English (USA)</option><option value="en-GB">English (UK)</option><option value="hi-IN">Hindi</option><option value="hi-en">Hinglish</option></select></label>{state?<p className="form-status">{state}</p>:null}<button className="button" type="button" disabled={form.useCase.trim().length<3||form.description.trim().length<20||state==="Generating workflow…"} onClick={generate}>Generate editable workflow</button></div></div>}
function CallModal({name,status,agentId,number,setNumber,state,close,call}:{name:string;status:string;agentId:number|null;number:string;setNumber:(v:string)=>void;state:string;close:()=>void;call:()=>void}){return <div className="modal-backdrop"><div className="product-modal" role="dialog" aria-label="Place a phone call"><div className="panel-head"><div><small>PHONE TEST</small><h2>Call with {name}</h2></div><button type="button" onClick={close}>×</button></div><p>Uses a registered workspace caller ID and its configured LiveKit SIP trunk.</p><label>Destination<input value={number} placeholder="+14155550123" inputMode="tel" onChange={event=>setNumber(event.target.value)}/></label>{state?<p className="form-status">{state}</p>:null}<button className="button" type="button" disabled={!agentId||status!=="published"||!/^\+[1-9]\d{7,14}$/.test(number)} onClick={call}>Start phone call</button>{status!=="published"?<p className="secure-note">Publish and save the agent before placing a phone call.</p>:null}</div></div>}

function workflowValue(value:AgentRecord["workflow"]|undefined):Workflow{if(!value)return defaultWorkflow;if(Array.isArray(value))return{nodes:value.length?value:defaultWorkflow.nodes,edges:value.length>1?value.slice(1).map((node,index)=>({id:`legacy-${index}`,source:value[index].id,target:node.id})):[]};return{nodes:Array.isArray(value.nodes)?value.nodes:defaultWorkflow.nodes,edges:Array.isArray(value.edges)?value.edges:[]}}
function templatePreset(value:string|undefined){
 const common={globalPrompt:"Follow company policy, protect personal data, disclose that you are an AI assistant, and never invent customer data or tool results.",greeting:"Hello, how can I help today?"};
 if(value==="blank")return{...common,name:"Untitled Agent",objective:"Define what this agent should accomplish.",workflow:{nodes:[],edges:[]} as Workflow};
 if(value==="lead-qualification")return{...common,name:"Lead Qualification Agent",objective:"Qualify inbound leads, capture verified requirements, route high-intent prospects, and record a clear disposition.",greeting:"Hello! I can ask a few quick questions to find the right next step for you.",workflow:remapWorkflow({identity:["Introduce qualification","Disclose AI identity and ask permission to continue."],decision:["Assess lead fit","Branch on need, authority, timing, and verified eligibility."],action:["Capture qualified lead","Save only confirmed lead details through an approved CRM tool."],handoff:["Transfer sales-ready lead","Offer a human sales handoff when qualification criteria are met."],end:["Confirm next step","Recap the agreed follow-up and close politely."]})};
 if(value==="appointment-booking")return{...common,name:"Appointment Booking Agent",objective:"Find an eligible time, book or reschedule through an approved calendar, and confirm the appointment accurately.",greeting:"Hello! I can help you book, reschedule, or cancel an appointment.",workflow:remapWorkflow({identity:["Understand booking request","Ask what appointment is needed and collect only required details."],decision:["Check booking policy","Branch between booking, rescheduling, cancellation, or human help."],action:["Update approved calendar","Use the connected calendar and confirm the returned booking result."],handoff:["Escalate scheduling exception","Transfer requests that require staff approval."],end:["Confirm appointment","Repeat the confirmed date, time, timezone, and next step."]})};
 return{...common,name:"Customer Care Agent",objective:"Resolve customer requests accurately, use approved tools, and hand off safely when needed.",workflow:defaultWorkflow};
}
function remapWorkflow(updates:Record<string,[string,string]>):Workflow{return{nodes:defaultWorkflow.nodes.map(node=>updates[node.id]?{...node,label:updates[node.id][0],prompt:updates[node.id][1]}:{...node}),edges:defaultWorkflow.edges.map(edge=>({...edge}))}}
function toFlowNode(node:WorkflowNode,index:number):FlowNode<NodeData>{return{id:node.id,type:"default",position:node.position||{x:100+(index%3)*300,y:80+Math.floor(index/3)*190},data:{kind:node.type,label:node.label,prompt:node.prompt||"",config:node.config||{}},className:`flow-node flow-${node.type.toLowerCase()}`}}
function fromFlowNode(node:FlowNode<NodeData>):WorkflowNode{return{id:node.id,type:node.data.kind,label:node.data.label,prompt:node.data.prompt,position:node.position,config:node.data.config}}
function toFlowEdge(edge:WorkflowEdge):Edge{return{id:edge.id,source:edge.source,target:edge.target,label:edge.label,data:{condition:edge.condition||""},animated:edge.label==="after call"}}
function fromFlowEdge(edge:Edge):WorkflowEdge{return{id:edge.id,source:edge.source,target:edge.target,label:typeof edge.label==="string"?edge.label:"",condition:typeof edge.data?.condition==="string"?edge.data.condition:""}}
function nodeIcon(kind:string){return kind==="Router"?"◇":kind==="Guardrail"?"✓":kind==="Tool"?"↗":kind==="Webhook"?"⇢":kind==="QA"?"◎":kind==="Audio"?"♫":kind==="End"?"■":"✦"}
