"use client";
import {useState} from "react";
import Link from "next/link";
const tabs=["Overview","Brand","Website","Media","Languages","Providers","Plans"];
const locales=[["Arabic","ar","RTL"],["English (USA)","en-US","LTR"],["English (UK)","en-GB","LTR"],["Hindi","hi-IN","LTR"],["Hinglish","hi-en","Code-switch"]];
export default function AdminCMS(){
 const[tab,setTab]=useState("Overview"),[saved,setSaved]=useState(false),[status,setStatus]=useState(""),[brand,setBrand]=useState("Nexora"),[tagline,setTagline]=useState("AI agents that reason, speak & act."),[primary,setPrimary]=useState("#D9FF43"),[upload,setUpload]=useState(""),[logoKey,setLogoKey]=useState(""),[heroTitle,setHeroTitle]=useState("Build AI agents that reason, speak & act."),[heroBody,setHeroBody]=useState("One production platform to design, deploy, and govern autonomous voice and chat agents across your business."),[cta,setCta]=useState("Build your first agent");
 async function save(){setSaved(true);setStatus("");try{const response=await fetch("/api/cms/settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({settings:[{key:"brand.name",value:brand},{key:"brand.tagline",value:tagline},{key:"brand.primaryColor",value:primary},{key:"brand.logoKey",value:logoKey},{key:"home.heroTitle",value:heroTitle},{key:"home.heroBody",value:heroBody},{key:"home.primaryCta",value:cta}]})});if(!response.ok)throw new Error();setStatus("Changes saved securely");}catch{setStatus("Changes could not be saved. Please retry.");}setSaved(false)}
 async function uploadFile(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setUpload("Uploading…");const data=new FormData();data.append("file",f);data.append("alt",f.name);const r=await fetch("/api/cms/media",{method:"POST",body:data});if(r.ok){const d=await r.json() as {media?:{key?:string}};setLogoKey(d.media?.key||"");setUpload("Uploaded successfully — save changes to publish")}else setUpload("Upload unavailable until media storage is connected")}
 return <main className="cms"><aside className="cms-side"><Link className="brand" href="/"><span className="brand-mark">N</span><span>{brand.toUpperCase()}</span></Link><p>SAAS CONTROL CENTER</p>{tabs.map(t=><button key={t} className={tab===t?"on":""} onClick={()=>setTab(t)}><i>{["▦","◆","▤","▧","文","⌘","$ "][tabs.indexOf(t)]}</i>{t}</button>)}<Link className="cms-nav" href="/settings"><i>⚙</i><span>Settings</span></Link><span/><Link href="/studio">← Agent studio</Link></aside><section className="cms-main"><header><div><small>ADMINISTRATION</small><h1>{tab}</h1>{status&&<p role="status">{status}</p>}</div><div><button>Preview site</button><button className="save-btn" onClick={save} disabled={saved}>{saved?"Saving…":"Save changes"}</button></div></header>
 {tab==="Overview"&&<div className="cms-overview"><div className="metrics"><article><small>ACTIVE WORKSPACES</small><b>24</b><em>+12% this month</em></article><article><small>AGENT MINUTES</small><b>18.4k</b><em>71% of allowance</em></article><article><small>MONTHLY REVENUE</small><b>$6,840</b><em>+8.4% this month</em></article><article><small>PROVIDER HEALTH</small><b className="healthy">Operational</b><em>5/5 connected</em></article></div><div className="cms-grid"><article><h3>Launch checklist</h3>{["Brand and domain","Plans and usage limits","Payment provider","Email templates","Privacy and AI disclosures"].map((x,i)=><p key={x}><span>{i<2?"✓":"○"}</span>{x}<em>{i<2?"Complete":"Configure"}</em></p>)}</article><article><h3>Usage by language</h3>{locales.map((l,i)=><p key={l[1]}>{l[0]}<span className="usage"><i style={{width:`${[42,86,31,55,49][i]}%`}}/></span><em>{["12%","38%","9%","22%","19%"][i]}</em></p>)}</article></div></div>}
 {tab==="Brand"&&<div className="cms-form"><h2>Brand identity</h2><p>Change the product identity without editing code.</p><label>PRODUCT NAME<input value={brand} maxLength={80} onChange={e=>setBrand(e.target.value)}/></label><label>TAGLINE<input value={tagline} maxLength={180} onChange={e=>setTagline(e.target.value)}/></label><div className="split"><label>PRIMARY COLOR<input value={primary} maxLength={7} onChange={e=>setPrimary(e.target.value)}/></label><label>LOGO<input type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadFile}/><small>{upload}</small></label></div></div>}
 {tab==="Website"&&<div className="cms-form"><h2>Homepage content</h2><p>Edit the public website without changing source code.</p><label>HERO TITLE<input value={heroTitle} onChange={e=>setHeroTitle(e.target.value)}/></label><label>HERO DESCRIPTION<textarea value={heroBody} onChange={e=>setHeroBody(e.target.value)}/></label><label>PRIMARY BUTTON<input value={cta} onChange={e=>setCta(e.target.value)}/></label><h2 className="cms-subtitle">Other pages</h2>{["Platform","Solutions","Pricing","Security","Contact","Privacy Policy","Terms of Service"].map((p,i)=><div className="page-row" key={p}><span>≡</span><div><b>{p}</b><small>/{p.toLowerCase().replaceAll(" ","-")}</small></div><em>{i>4?"Draft":"Published"}</em><button>Edit</button></div>)}</div>}
 {tab==="Media"&&<div className="cms-form"><h2>Media library</h2><p>Upload logos, web images, agent avatars, and social cards.</p><label className="drop">＋<b>Upload an image</b><small>PNG, JPG or WebP · Maximum 5 MB</small><input type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadFile}/></label><p>{upload}</p></div>}
 {tab==="Languages"&&<div className="cms-form wide"><h2>Language and locale policies</h2><p>Every agent can use a fixed locale or automatic language detection.</p>{locales.map(l=><div className="language-row" key={l[1]}><span>●</span><b>{l[0]}</b><code>{l[1]}</code><em>{l[2]}</em><select><option>Enabled</option><option>Disabled</option></select></div>)}</div>}
 {tab==="Providers"&&<div className="cms-form wide"><h2>Provider routing</h2><p>Drag providers into priority order. A failed provider automatically falls through without changing the agent workflow.</p>{[["LLM","OpenAI","Anthropic","Google Gemini"],["Speech-to-text","ElevenLabs Scribe","Deepgram","Gnani"],["Text-to-speech","ElevenLabs","OpenAI Voice","Deepgram"],["Realtime","LiveKit Cloud","Self-hosted LiveKit","Daily"],["Telephony","LiveKit SIP","Twilio","Telnyx"]].map(r=><div className="provider-row" key={r[0]}><b>{r[0]}</b>{r.slice(1).map((x,i)=><span key={x}><i>{i+1}</i>{x}<em>{i===0?"Primary":"Fallback"}</em></span>)}</div>)}</div>}
 {tab==="Plans"&&<div className="cms-form wide"><h2>Plans and limits</h2><p>Control subscriptions, included usage, overages, and feature access.</p><div className="plan-grid">{[["Starter","$49","2 agents","500 min"],["Growth","$199","10 agents","3,000 min"],["Business","$599","Unlimited","10,000 min"]].map(p=><article key={p[0]}><small>{p[0]}</small><b>{p[1]}<em>/mo</em></b><p>{p[2]}</p><p>{p[3]}</p><button>Edit plan</button></article>)}</div></div>}
 </section></main>
}
